# Generated by Django 4.2.6 on 2023-10-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('response_status', models.CharField(choices=[('0', 'Not Good'), ('1', 'Good'), ('2', 'Perfect')], default='0', max_length=20)),
            ],
        ),
    ]
